### ISSUE TITLE
Can we remove this default css?

### ISSUE THREAD

**Issue by mattjmorrison** [ember-cli/ember-cli#3152]
Every time I spin up a new ember-cli app I end up having to go and delete this. Is there some reason for it being there?

https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/app/styles/app.css#L2

```css
html, body {
  margin: 20px;
}
```
