### ISSUE TITLE
CSS dependencies are compiled in alphabetical order by package name instead of by dependency tree

### ISSUE THREAD

**Issue by taras** [ember-cli/ember-cli#4523]
I have an addon called `ember-cli-ember-table` that has `ember-table` as a dependency and it provides custom CSS that override the default CSS provided by `ember-table`. For this to work, the overriding CSS needs to be included in the vendor.css after `ember-table`. This doesn't work because EmberCLI includes CSS from dependencies in alphabetical order.

I created a few test repositories to show that this the case.

- [/taras/css-test-app](https://github.com/taras/css-test-app) - app with 2 dependencies (addon-b & addon-c)
- [/taras/addon-b](https://github.com/taras/addon-b) - addon has addon-a as dependency
- [/taras/addon-c](https://github.com/taras/addon-c) - addon has addon-d as a dependency

I would expect the CSS from *addon-d* to display before *addon-c* because it's a dependency, but this is not the case.

Here is what the generated CSS looks like

```css
/* addon a */
button {
  color: red;
}
/*# sourceMappingURL=addon-a.css.map */
/** addon b **/
button {
  color: green;
}

/* addon-c */
/* addon-c has addon-d as a dependency, so this should go after addon-d's css */
h2 {
  color: blue;
}

/* addon-d */
h2 {
  color: purple;
}

```
