### ISSUE TITLE
2.16 - test hangs at end with chrome v62 headless on CI

### ISSUE THREAD

**Issue by BryanCrotaz** [ember-cli/ember-cli#7514]
Works on desktop (macOS), hangs on CI (shippable) after running all the tests. Using Chrome 62.0

testem.js
```
/* eslint-env node */
module.exports = {
  test_page: 'tests/index.html?hidepassed',
  disable_watching: true,
  launch_in_ci: [
    'Chrome'
  ],
  launch_in_dev: [
    'Chrome'
  ],
  browser_start_timeout: 60,
  browser_args: {
    Chrome: {
      mode: 'ci',
      args: [
        '--disable-gpu',
        '--disable-web-security', // optional, since chrome 60+
        '--headless',
        '--incognito', // optional
        '--remote-debugging-address=0.0.0.0',
        '--remote-debugging-port=9222',
        '--window-size=1440,900',
        '--no-sandbox'
      ]
    },
  }
};
```

Desktop Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.16.2
http_parser: 2.7.0
node: 8.9.1
v8: 6.1.534.47
uv: 1.15.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2m
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b
os: darwin x64
5.6.0
-bash: yarn: command not found
```

CI Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.16.2
http_parser: 2.7.0
node: 8.9.3
v8: 6.1.534.48
uv: 1.15.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2n
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b
os: linux x64
5.6.0
1.2.1
```

**Comment by BryanCrotaz** [comment]
Using this yaml on Shippable
```
language: node_js

env:
  - CI=true COVERAGE=true

node_js:
  - "8.9"

build:
  ci:
  - rm -rf node_modules
  - node --version
  - npm --version
  - if [ $(npm --version) != "5.6.0" ]; then npm install -g npm@5.6.0; fi;
  - npm config set spin false
  - export PATH=$PATH:node_modules/.bin
  # install chrome headless
  - CHROME_DRIVER_VERSION=`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`
  # Install dependencies.
  - apt-get update
  - |
    if apt -qq list unzip 2>/dev/null | grep -q installed ; then
      apt-get install -y unzip
    fi
  - |
    if apt -qq list openjdk-8-jre-headless 2>/dev/null | grep -q installed ; then
      apt-get install -y openjdk-8-jre-headless
    fi
  - |
    if apt -qq list xvfb 2>/dev/null | grep -q installed ; then
      apt-get install -y xvfb
    fi
  - |
    if apt -qq list libxi6 2>/dev/null | grep -q installed ; then
      apt-get install -y libxi6
    fi
  - |
    if apt -qq list libgconf-2-4 2>/dev/null | grep -q installed ; then
      apt-get install -y libgconf-2-4
    fi
  # Install Chrome.
  - curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add
  - echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
  - apt-get -y update
  - |
    if apt -qq list google-chrome-stable 2>/dev/null | grep -q installed ; then
      apt-get install -y google-chrome-stable
    fi
  # Install ChromeDriver.
  - wget -N http://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - mv -f ~/chromedriver /usr/local/bin/chromedriver
  - chown root:root /usr/local/bin/chromedriver
  - chmod 0755 /usr/local/bin/chromedriver

  # install dependencies
  - npm install

  # pin testem version to 1.13.0
  - npm ls testem
  # - sed 's/1.18.4/1.13.0/g' node_modules/ember-cli/package.json
  # - npm install
  # - npm ls testem

  - bower install --allow-root
  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage

  # test
  - ember version --verbose && npm --version && yarn --version

  - ember test ci #--silent -r xunit > shippable/testresults/result.xml

  cache: true

  cache_dir_list:
    - $SHIPPABLE_BUILD_DIR/node_modules
    - $SHIPPABLE_BUILD_DIR/bower_components

  on_success:

  on_failure:
```
