### ISSUE TITLE
Remove implicit CSS minification

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-cli#8457]
In the current state (v3.7.x) Ember CLI automatically minifies CSS files using [`clean-css`](https://github.com/jakubpawlowicz/clean-css) when building for the `production` environment. 

For this to work Ember CLI has a direct dependency on https://github.com/ember-cli/ember-cli-preprocess-registry/ v3.x, which falls back to `broccoli-clean-css` when no other `minify-css` preprocessor is found in the registry. One example of such a preprocessor is https://github.com/ember-cli/ember-cli-clean-css.

The goal of this issue is to remove the fallback and make CSS minification an explicit thing, similar to what we do with `ember-cli-uglify` for JS code.

### Todo

- [ ] add https://github.com/ember-cli/ember-cli-clean-css to several test apps and check if the minified CSS output is the same (or possibly better)
- [ ] if needed, port https://github.com/ember-cli/ember-cli-preprocess-registry/pull/54 to `ember-cli-clean-css` (/cc @Emrvb)
- [ ] add `ember-cli-clean-css` as a dependency to the `app` and `addon` blueprints
- [ ] (after ☝️!) update `ember-cli-preprocess-registry` to a version without the `clean-css` fallback

### Related

- https://github.com/ember-cli/ember-cli/issues/8359

**Comment by RichardOtvos** [comment]
@t-sauer Can I take this? This would be my first issue in ember-cli, but would be happy to help

**Comment by t-sauer** [comment]
@RichardOtvos I think you mentioned the wrong person 😄

**Comment by RichardOtvos** [comment]
sorry @t-sauer ! 😬 
@Turbo87 can I take this? If it helps I'm a lot better at coding than mentioning people in github issue comments 😁

**Comment by chendraayan** [comment]
Is there any workaround for this, until this enhancement is released?

**Comment by void-mAlex** [comment]
let me have a go at this :)

**Comment by void-mAlex** [comment]
so finally got around to spending some time on this and ran into some issues
what I've done so far was the prep work to ensure the output is the same
I've gone through most of the repos on the ember-learn and ember-guides orgs cloned them and did two builds; one as is and one after I've added https://github.com/ember-cli/ember-cli-clean-css
for the most part what I've observed is that the addon does a bit more in terms of optimizing the css classes removing redundant ones and adding the leftover properties as standalone if needed (not sure if that's intended or not)

but the worrying part is that it does not handle the relative `url()` function well at all and here is an example

_all examples are from SuperRentals repo [https://github.com/ember-learn/super-rentals](url)_

```css
.tomster {
  background: url(../assets/images/teaching-tomster-756a14cc8225582bf530b5d0c624db4d.png) no-repeat;
  background-size: contain;
  height: 200px;
  width: 200px;
  top: -25px
}
```
becomes
```css
.tomster {
  background: url(../../../../tmp/broccoli-1189SeGOWMQ9D4Gu/out-201-funnel/assets/images/teaching-tomster-756a14cc8225582bf530b5d0c624db4d.png);
  background-size: contain;
  background-repeat: no-repeat;
  height: 200px;
  width: 200px;
  position: relative;
  top: -25px
}
```
for absolute urls (at least on the builds on my machine it's behaving)

another big difference is that it's not removing duplicate property declarations
unprocessed file:
```css
/**
 * Top Navigation
 */

.menu {
  height: 4em;
  background-color: #677ae4;
  background-color: #05526A;
  background-color: #e46855;
}
```
original css output
```css

.menu {
  height: 4em;
  background-color: #e46855
}
```
addon css output
```css
.menu {
  height: 4em;
  background-color: #677ae4;
  background-color: #05526a;
  background-color: #e46855
}
```
which this won't hurt the final appearance of the app it does mean that it might ever so slightly increase the css size

just to confirm I've done these tests on the master branch of the addon as the published version is using babel version 5 and throws additional errors at build time.

@locks @rwjblue I'll try to look at why the addon is not handling relative urls, but any guidance would be much appreciated, I do believe that is a showstopper  for this ticket going forward
